title:            me, myself & andrei
description:      "But don't think twice, it's alright!"
url:              http://blog.andreineculau.com
baseurl:
signoff:          Andrei
disqus_shortname: blogandreineculaucom
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name: About
    url: http://andreineculau.com

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Europe/Stockholm
future: true
show_drafts: false
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax # can't change

  # extensions:
  # - autolink
  # - disable_indented_code_blocks
  # - fenced_code_blocks
  # - no_intra_emphasis
  # - strikethrough
  # - superscript
  # - underline

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:year/:month/:day/:title
relative_permalinks: false

# github-pages can't change. https://help.github.com/articles/configuring-jekyll/
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false

gems:
  - jekyll-coffeescript
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji
