title:            "Andrei Neculau's blog"
description:      "I'd rather be an optimist and a fool than a pessimist and right."
url:              http://blog.andreineculau.com
baseurl:
signoff:          Andrei
disqus_shortname: blogandreineculaucom
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name: About
    url: http://andreineculau.com

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Europe/Stockholm
future: true
show_drafts: false
markdown: redcarpet
redcarpet:
  extensions:
  - autolink
  - disable_indented_code_blocks
  - fenced_code_blocks
  - no_intra_emphasis
  - strikethrough
  - superscript
  - underline

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:year/:month/:day/:title
relative_permalinks: false

safe: true
lsi: false

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
